# Generated by Django 5.2.3 on 2025-06-25 02:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cve_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('ap_paterno', models.CharField(max_length=40)),
                ('ap_materno', models.CharField(max_length=40)),
                ('rfc', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('cve_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('ap_paterno', models.CharField(max_length=40)),
                ('ap_materno', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('cve_estados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estados_fase',
            fields=[
                ('cve_estado_fase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estados_obra',
            fields=[
                ('cve_estados_obra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estados_tarea',
            fields=[
                ('cve_estados_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='funciones',
            fields=[
                ('cve_funciones', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='materiales',
            fields=[
                ('cve_materiales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=60)),
                ('fecha_registro', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('cve_paises', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='provedores',
            fields=[
                ('cve_provedores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('cve_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tipos_material',
            fields=[
                ('cve_tipos_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unidades_medida',
            fields=[
                ('cve_unidades_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cve_personas', models.AutoField(primary_key=True, serialize=False)),
                ('ap_paterno', models.CharField(max_length=40)),
                ('ap_materno', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cve_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.roles')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='habilidades_funciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.empleados')),
                ('cve_funciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.funciones')),
            ],
        ),
        migrations.CreateModel(
            name='detalles_compras',
            fields=[
                ('cve_detalles_compras', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('cve_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.materiales')),
            ],
        ),
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('cve_municipios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cve_estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.estados')),
            ],
        ),
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('cve_ciudades', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cve_municipios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.municipios')),
            ],
        ),
        migrations.CreateModel(
            name='obras',
            fields=[
                ('cve_obras', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
                ('calle', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('presupuesto', models.FloatField()),
                ('porcentaje_avance', models.FloatField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('cve_ciudades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.ciudades')),
                ('cve_clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.clientes')),
                ('cve_estados_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.estados_obra')),
                ('cve_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_obras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fases',
            fields=[
                ('cve_fases', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('porcentaje_avance', models.IntegerField()),
                ('cve_estado_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.estados_fase')),
                ('cve_obras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obras')),
            ],
        ),
        migrations.CreateModel(
            name='empleados_obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.empleados')),
                ('cve_funciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.funciones')),
                ('cve_obras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obras')),
            ],
        ),
        migrations.AddField(
            model_name='estados',
            name='cve_paises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.paises'),
        ),
        migrations.CreateModel(
            name='compras',
            fields=[
                ('cve_compras', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('total', models.FloatField()),
                ('cve_detalles_comprad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.detalles_compras')),
                ('cve_obras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obras')),
                ('cve_provedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.provedores')),
            ],
        ),
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('cve_tareas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('porcentaje_avance', models.IntegerField()),
                ('cve_estados_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.estados_tarea')),
                ('cve_fases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.fases')),
            ],
        ),
        migrations.CreateModel(
            name='evidencias',
            fields=[
                ('cve_evidencias', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField()),
                ('cve_tareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.tareas')),
            ],
        ),
        migrations.AddField(
            model_name='materiales',
            name='cve_tipos_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.tipos_material'),
        ),
        migrations.CreateModel(
            name='materiales_obras',
            fields=[
                ('cve_materiales_obras', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('fecha_uso', models.DateTimeField()),
                ('cve_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.materiales')),
                ('cve_obras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obras')),
                ('cve_unidades_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.unidades_medida')),
            ],
        ),
        migrations.AddField(
            model_name='materiales',
            name='cve_unidades_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.unidades_medida'),
        ),
    ]
